version: 0.1.{build}.0

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
build:
  project: Src/couchbase-net-linq.sln
  
after_test:
  - ps: .\Nuget\pack.ps1
